defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: asnote_development

test:
  <<: *defaults
  database: asnote_test

production:
  <<: *defaults
  database: asnote_production
  #database: asnote_development
